---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: srv-storage
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem # Mount volume into Pod as a directory.
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: ~/srv # Path to the directory this PV refers to.
  nodeAffinity: # nodeAffinity is required when using local volumes.
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mp7


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: srv-storage-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi



---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  labels:
    name: busybox-pod
spec:
  containers:
  - name: busybox
    image: docker.io/busybox
    # command: ['sh', '-c', 'echo "The local volume is mounted!" > /mnt/test.txt && sleep 3600']
    volumeMounts:
      - name: srv-local
        mountPath: /mnt
  volumes:
    - name: srv-local
      persistentVolumeClaim:
        claimName: srv-storage-claim
