apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-pv
  labels:
    type: local
    purpose: seafile-storage
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
