---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe-depl
  labels:
    app: tictactoe
    v: 0.0.3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tictactoe
    spec:
      containers:
      - name: tictactoe
        image: docker.io/zoosmand/tictactoe:v3
        ports:
          - containerPort: 80
        resources:.
          limits:
            memory: 128Mi
            cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: tictactoe-serv
  labels:
    app: tictactoe
spec:
  selector:
    app: tictactoe
  #type: LoadBalancer
   type: NodePort
  ports:
    - protocol: TCP
      name: "http"
      port: 80
      targetPort: 80
      nodePort: 30066
