apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {
      “asart.local”: [“192.168.203.10”],
      “mira.asart.local”: [“192.168.203.10”]
    }
  upstreamNameservers: |
    [“8.8.8.8”, “8.8.4.4”]