apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {
      “asart.local”: [“10.16.10.14”],
      “home.asart.local”: [“192.168.200.2”],
      “mira.asart.local”: [“192.168.203.10”]
    }
  
  upstreamNameservers: |
    [“192.168.203.10”, "192.168.200.2", "10.16.10.14", "8.8.8.8", "8.8.4.4"]