version: "3.9"

services: 
  elasticsearch:
    container_name: els-elasticsearch
    image: elasticsearch:7.13.2
    volumes: 
      - ~/srv/els/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - db_data:/usr/share/elasticsearch/data/
    restart: always
    environment: 
      discovery.type: single-node
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3  
    networks: 
      - default

  kibana:
    container_name: els-kibana
    depends_on: 
      - elasticsearch
    image: kibana:7.13.2
    volumes: 
      - ~/srv/els/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    restart: always
    environment: 
      ELASTICSEARCH_HOSTS: http://els-elasticsearch:9200
    ports: 
      - "5601:5601"
    networks: 
      - default

  logstash:
    container_name: els-logstash
    depends_on: 
      - elasticsearch
    image: logstash:7.13.2
    volumes: 
      - ~/srv/els/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ~/srv/els/logstash/config/conf.d/:/usr/share/logstash/config/conf.d/
      - ~/srv/els/logstash/templates/:/usr/share/logstash/pipeline/templates
    restart: always
    ports: 
      - "5044:5044"
      - "5045:5045"
      - "5046:5046"
    networks: 
      - default
    
    
networks:
  default:
    driver: bridge
    name: els-net

volumes: 
  db_data:
