---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-ap-depl
  labels:
    app: ubuntu-ap
    v: 0.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ubuntu-ap
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ubuntu-ap
    spec:
      containers:
      - name: ubuntu-ap
        image: docker.io/zoosmand/ubuntu_ap:latest
        ports:
          - containerPort: 80
        resources: 
          limits:
            memory: 128Mi
            cpu: 500m

