## @section Global parameters
##
global:
  imageRegistry: "docker.io"
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""
  namespaceOverride: ""

  useStatefulSet: false

## @param extraDeploy Array of extra objects to deploy with the release
##
extraDeploy: []
## @param commonLabels Add labels to all the deployed resources (sub-charts are not considered). Evaluated as a template
##
commonLabels: {}
## @param commonAnnotations Common annotations to add to all Mongo resources (sub-charts are not considered). Evaluated as a template
##
commonAnnotations: {}

## @section Common parameters
##

## @param nameOverride String to partially override mongodb.fullname template (will maintain the release name)
##
nameOverride: ""
## @param fullnameOverride String to fully override mongodb.fullname template
##
fullnameOverride: ""

release:
  name: "TraditionalGreekTavern"
  ver: 0.0.1

auth:
  enabled: true
  secretKeyRef: "mongodb-secret"
  rootUser: "admin"
  rootPwd: "password"

  username: ""
  password: ""
  database: ""

map:
  configMapKeyRef: "mongodb-configmap"


image:
  registry: "docker.io"
  mongodbImage: "mongo"
  mongoExpressImage: "mongo-express"

containers:
  mongodbPort: 27017
  mongodbPublicPort: 30001
  mongoExpressPort: 8081
  mongoExpressPublicPort: 30000