apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mongodb.configMapKeyRef" . }}
  namespace: {{ template "mongodb.namespace" . }}
  labels:
    name: {{ include "mongodb.cmap" . }}
data:
  database_url: {{ include "mongodb.net" . }}
