apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo-express.net" . }}
  labels:
    app: {{ include "mongo-express.net" . }}
spec:
  selector:
    app: {{ include "mongo-express.selector" . }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.containers.mongoExpressPort }}
      targetPort: {{ .Values.containers.mongoExpressPort }}
      nodePort: {{ .Values.containers.mongoExpressPublicPort }}
