apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.net" . }}
  labels:
    app: {{ include "mongodb.net" . }}
spec:
  selector:
    app: {{ include "mongodb.selector" . }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: {{ .Values.containers.mongodbPort }}
      targetPort: {{ .Values.containers.mongodbPort }}
      nodePort: {{ .Values.containers.mongodbPublicPort }}
