apiVersion: apps/v1
kind: {{ if .Values.global.useStatefulSet }}StatefulSet{{- else }}Deployment{{- end }}
metadata:
  name: {{ include "mongodb.meta.name" . }}
  labels:
    app: {{ include "mongodb.selector" . }}
    app.kubernetes.io/component: mongodb
    namespace: {{ include "mongodb.namespace" . }}
    release.name: {{ .Values.release.name }} 
    release.ver: {{ .Values.release.ver }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mongodb.selector" . }}
  {{- if .Values.global.useStatefulSet }}
  serviceName: {{ include "mongodb.service.name" . }}
  updateStrategy:
    rollingUpdate: null
    type: OnDelete
  {{- else }}
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 25%
    type: RollingUpdate
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ include "mongodb.selector" . }}
    spec:
      containers:
      - name: {{ include "mongodb.container" . }}
        image: {{ include "mongodb.image" . }}
        ports:
          - containerPort: {{ .Values.containers.mongodbPort }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "mongodb.secretKeyRef" . }}
              key: mongodb-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mongodb.secretKeyRef" . }}
              key: mongodb-root-password
        resources: 
          limits:
            memory: 512Mi
            cpu: 1
