apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-depl
  labels:
    app: {{ include "mongo-express.selector" . }}
    app.kubernetes.io/component: mongo-express
    namespace: {{ include "mongodb.namespace" . }}
    release.name: {{ .Values.release.name }} 
    release.ver: {{ .Values.release.ver }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "mongo-express.selector" . }}
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "mongo-express.selector" . }}
    spec:
      containers:
      - name: {{ include "mongo-express.container" . }}
        image: {{ include "mongo-express.image" . }}
        ports:
          - containerPort: {{ .Values.containers.mongoExpressPort }}
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: {{ template "mongodb.secretKeyRef" . }}
              key: mongodb-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "mongodb.secretKeyRef" . }}
              key: mongodb-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: {{ template "mongodb.configMapKeyRef" . }}
              key: database_url
        resources: 
          limits:
            memory: 128Mi
            cpu: 500m
