apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mongodb.secretKeyRef" . }}
  namespace: {{ template "mongodb.namespace" . }}
  labels:
    app.kubernetes.io/component: mongodb
    name: {{ include "mongodb.secrets" . }}
type: Opaque
data:
  mongodb-root-username: {{ .Values.auth.rootUser | toString | b64enc }}
  mongodb-root-password: {{ .Values.auth.rootPwd | toString | b64enc }}
