---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-depl
  labels:
    app: nginx
    v: 0.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx:1.16
        ports:
          - containerPort: 80
            name: "http"
        resources: 
          limits:
            memory: 128Mi
            cpu: 500m



---
apiVersion: v1
kind: Service
metadata:
  name: nginx-serv
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  # type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
